name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Generate .env file
      run: |
        cat <<EOF > .env
        PORT=8080
        UPLOAD_PATH=./uploads

        MYSQL_HOST=35.226.9.113
        MYSQL_USER=angel
        MYSQL_PASSWORD=Takitol1986.
        MYSQL_DATABASE=canciones
        MYSQL_PORT=3306
        EOF

    - name: Build and tag Docker image
      run: |
        IMAGE_TAG=$(echo $GITHUB_SHA | cut -c1-7)
        docker build -t ${{ secrets.DOCKER_USERNAME }}/api-canciones:$IMAGE_TAG .

    - name: Push Docker image
      run: |
        IMAGE_TAG=$(echo $GITHUB_SHA | cut -c1-7)
        docker push ${{ secrets.DOCKER_USERNAME }}/api-canciones:$IMAGE_TAG
